"""
Database model for Executive Summary Report (Fleet Health) recipients.

These recipients receive the weekly one-page PDF report generated by
scripts/generate_fleet_health_report.py (via the systemd timer or ad-hoc
from the GUI).
"""

from sqlalchemy import Column, Integer, String, DateTime, Boolean
from datetime import datetime, timezone
from ..database import Base


class ExecutiveReportRecipient(Base):
    __tablename__ = "executive_report_recipients"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Email address (unique)
    email = Column(String(255), nullable=False, unique=True, index=True)

    # When the recipient was added via the GUI
    added_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    # Last time an ad-hoc or scheduled report was successfully emailed to this address
    last_sent_at = Column(DateTime, nullable=True)


class ExecutiveReportConfig(Base):
    """Minimal config for Executive Summary Report: from email and basic schedule."""
    __tablename__ = "executive_report_config"

    id = Column(Integer, primary_key=True, autoincrement=True)
    from_email = Column(String(255), nullable=True)
    schedule_enabled = Column(Boolean, default=True)
    schedule_day = Column(Integer, default=0)  # 0=Mon ... 6=Sun
    schedule_hour = Column(Integer, default=8)
    schedule_minute = Column(Integer, default=0)
    last_scheduled_sent_at = Column(DateTime, nullable=True)
