"""
Database model for Executive Summary Report (Fleet Health) recipients.

These recipients receive the weekly one-page PDF report generated by
scripts/generate_fleet_health_report.py (via the systemd timer or ad-hoc
from the GUI).
"""

from sqlalchemy import Column, Integer, String, DateTime
from datetime import datetime, timezone
from ..database import Base


class ExecutiveReportRecipient(Base):
    __tablename__ = "executive_report_recipients"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Email address (unique)
    email = Column(String(255), nullable=False, unique=True, index=True)

    # When the recipient was added via the GUI
    added_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    # Last time an ad-hoc or scheduled report was successfully emailed to this address
    last_sent_at = Column(DateTime, nullable=True)
