"""
Database model for Executive Summary Report (Fleet Health) recipients.

These recipients receive the weekly one-page PDF report generated by
scripts/generate_fleet_health_report.py (via the systemd timer or ad-hoc
from the GUI).
"""

from sqlalchemy import Column, Integer, String, DateTime, Boolean
from datetime import datetime, timezone
from ..database import Base


class ExecutiveReportRecipient(Base):
    __tablename__ = "executive_report_recipients"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Email address (unique)
    email = Column(String(255), nullable=False, unique=True, index=True)

    # When the recipient was added via the GUI
    added_at = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)

    # Last time an ad-hoc or scheduled report was successfully emailed to this address
    last_sent_at = Column(DateTime, nullable=True)


class ExecutiveReportConfig(Base):
    """Single-row configuration for the Executive Summary Report.

    Includes from_email for custom From: header, and schedule settings
    for cadence (day of week, time). The generator script honors these.
    """
    __tablename__ = "executive_report_config"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # Custom From address (e.g. reports@company.com). If set, passed to mail command.
    from_email = Column(String(255), nullable=True)

    # Scheduled delivery enabled
    schedule_enabled = Column(Boolean, default=True)

    # Day of week: 0=Mon ... 6=Sun (matches Python weekday, systemd Mon=1 but we normalize)
    schedule_day = Column(Integer, default=0)  # Monday default to match old timer

    # Hour 0-23, minute 0-59
    schedule_hour = Column(Integer, default=8)
    schedule_minute = Column(Integer, default=0)

    # Last time a scheduled report was sent
    last_scheduled_sent_at = Column(DateTime, nullable=True)
