"""
PuppetDB API client service.

Provides an async HTTP client for communicating with PuppetDB's v4 REST
API over mutual-TLS (using the Puppet agent's SSL certificate and key).
This is the sole gateway for all PuppetDB queries in the application —
every router that needs PuppetDB data goes through the singleton
puppetdb_service instance defined at the bottom of this module.

The client is lazily initialised on first use and reused for the lifetime
of the process. Connection failures are logged and re-raised so that
callers (routers) can return appropriate HTTP error responses.

Security note: several methods accept a report_hash parameter that gets
interpolated into PQL query strings. Report hashes are hex strings
generated by PuppetDB, but because they arrive as user-supplied URL path
parameters, they are validated with a strict hex-only regex before
interpolation to prevent PQL injection.
"""
import asyncio
import json
import re
import httpx
import ssl
import logging
from typing import Any, Dict, List, Optional
from copy import deepcopy
from ..config import settings
from ..utils.ttl_cache import get_or_set as cache_get_or_set
from ..utils.jolokia import (
    escape_jolokia_path,
    jolokia_row_value,
    normalize_mbean,
    pick_http_latency_beans,
    timer_present,
    unescape_jolokia_mbean,
)

logger = logging.getLogger(__name__)

# Report hashes are hex. OpenVoxDB uses SHA-256 (64); older PDB used SHA-1 (40).
# URLs often carry a prefix. Reject anything that is not 7–64 hex chars.
_SAFE_HEX_HASH = re.compile(r'^[a-f0-9]{7,64}$')


def _validate_report_hash(report_hash: str) -> str:
    """Validate a report hash (or unique prefix) before PQL interpolation."""
    h = (report_hash or "").strip().lower()
    if not h or not _SAFE_HEX_HASH.match(h):
        raise ValueError("Invalid report hash: must be 7–64 hex characters")
    return h


def _cert_aliases(certname: str) -> List[str]:
    """Exact certname plus short host. Callers must not treat short names as
    globally unique — ovca1.pdxc… and ovca1.atlc… share ``ovca1``.
    """
    c = (certname or "").strip().lower()
    if not c:
        return []
    names = [c]
    short = c.split(".")[0]
    if short and short not in names:
        names.append(short)
    return names


def _short_host(certname: str) -> str:
    return (certname or "").strip().lower().split(".")[0]


def _report_ts(row: Optional[Dict]) -> str:
    if not row:
        return ""
    return str(row.get("receive_time") or row.get("end_time") or row.get("start_time") or "")


def _fold_newest_report(out: Dict[str, Dict], row: Any) -> None:
    """Keep the newest report document per certname (by receive_time).

    ``latest_report?`` is a denormalized flag. On clustered OpenVoxDB
    (Spock / multi-writer) it can stick on an older ``failed`` row after
    a later unchanged/changed report exists. Newest ``receive_time`` wins.
    """
    if not isinstance(row, dict):
        return
    key = str(row.get("certname") or "").strip().lower()
    if not key:
        return
    prev = out.get(key)
    if prev is None or _report_ts(row) >= _report_ts(prev):
        out[key] = row


def _project_rows(rows: Any, fields_json: str) -> List[Dict]:
    """Normalize PuppetDB ``extract`` rows to dicts.

    Some PuppetDB versions return a list of maps; others return positional
    arrays in the same order as the extract field list. Callers that only
    read a few columns must not depend on which shape came back.
    """
    if not isinstance(rows, list):
        return []
    try:
        keys = json.loads(fields_json)
    except (TypeError, ValueError):
        keys = []
    if not isinstance(keys, list):
        keys = []
    out: List[Dict] = []
    for row in rows:
        if isinstance(row, dict):
            out.append(row)
            continue
        if isinstance(row, (list, tuple)) and keys:
            out.append({
                str(keys[i]): row[i]
                for i in range(min(len(keys), len(row)))
            })
    return out


def _pick_report_for_node(certname: str, by_exact: Dict[str, Dict]) -> Optional[Dict]:
    """Resolve a node's latest report without cross-site short-name collisions.

    Prefer exact certname. Fall back to short hostname only when exactly one
    report in *by_exact* uses that short name.
    """
    key = (certname or "").strip().lower()
    if not key:
        return None
    if key in by_exact:
        return by_exact[key]
    short = _short_host(key)
    if not short:
        return None
    matches = [row for cn, row in by_exact.items() if _short_host(cn) == short]
    if len(matches) == 1:
        return matches[0]
    return None


class PuppetDBService:
    """Async client for PuppetDB v4 API."""

    def __init__(self):
        self.base_url = f"https://{settings.puppetdb_host}:{settings.puppetdb_port}"
        self._client: Optional[httpx.AsyncClient] = None

    def _create_ssl_context(self) -> ssl.SSLContext:
        ctx = ssl.create_default_context(cafile=settings.puppet_ssl_ca)
        ctx.load_cert_chain(
            certfile=settings.puppet_ssl_cert,
            keyfile=settings.puppet_ssl_key,
        )
        return ctx

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None or self._client.is_closed:
            # Keep a modest connection pool warm so multi-chart pages that
            # fan out to PuppetDB reuse TLS sessions instead of re-handshaking.
            self._client = httpx.AsyncClient(
                base_url=self.base_url,
                verify=self._create_ssl_context(),
                timeout=httpx.Timeout(30.0, connect=5.0),
                limits=httpx.Limits(
                    max_connections=40,
                    max_keepalive_connections=20,
                    keepalive_expiry=30.0,
                ),
                trust_env=False,
            )
        return self._client

    async def close(self):
        if self._client and not self._client.is_closed:
            await self._client.aclose()

    async def _query(self, endpoint: str, query: Optional[str] = None,
                     params: Optional[Dict] = None) -> Any:
        """Execute a PuppetDB query.

        When endpoint is empty, this sends a PQL query to the base
        /pdb/query/v4 endpoint (no trailing slash — PuppetDB returns
        404 for the trailing-slash variant).
        """
        client = await self._get_client()
        url = f"/pdb/query/v4/{endpoint}".rstrip("/")
        request_params = params or {}
        if query:
            request_params["query"] = query
        try:
            resp = await client.get(url, params=request_params)
            resp.raise_for_status()
            return resp.json()
        except httpx.HTTPStatusError as e:
            if e.response.status_code == 404:
                logger.info("PuppetDB 404 for %s", url)
            else:
                logger.error(
                    "PuppetDB HTTP error: %s", e.response.status_code,
                )
            raise
        except Exception as e:
            logger.error(f"PuppetDB connection error: {e}", exc_info=True)
            raise

    # ─── Nodes ──────────────────────────────────────────────

    async def get_nodes(self, query: Optional[str] = None,
                        include_inactive: bool = False,
                        overlay_reports: bool = True) -> List[Dict]:
        """Get nodes from PuppetDB.

        By default, only returns active nodes (not deactivated or expired)
        and deduplicates by certname. PuppetDB retains deactivated/expired
        node records until they are purged, so filtering is essential to
        avoid displaying ghost nodes that have been removed from the Puppet
        CA but not yet purged from PuppetDB.

        Filtering is done in Python after fetch to guarantee correctness
        regardless of PuppetDB version or PQL operator support.

        Set overlay_reports=False when the caller only needs membership
        (Insights | Inventory) and must not wait on peer report merges.
        """
        all_nodes = await self._query("nodes", query=query)

        if not include_inactive:
            all_nodes = [
                n for n in all_nodes
                if not n.get("deactivated") and not n.get("expired")
            ]

        # Deduplicate by certname (case-insensitive, stripped)
        seen: set = set()
        unique = []
        for node in all_nodes:
            key = node.get("certname", "").strip().lower()
            if key and key not in seen:
                seen.add(key)
                unique.append(node)

        # Node index latest_report_status can lag behind (or stick on failed)
        # after a later successful run. Overlay the actual latest report doc.
        if overlay_reports:
            await self._overlay_latest_report_status(unique)
        return unique

    async def get_live_nodes(self) -> List[Dict]:
        """Return the fleet as active OpenVoxDB nodes (PuppetDB is SSoT).

        Overview | Nodes, Insights | Inventory, ENC Unclassified /
        reconciliation, Dashboard, and Node Health all use this list.

        - **Active PuppetDB** — ``certnames`` rows that are not deactivated
          or expired (an agent that has reported). This is the CMDB.
        - **No CA intersection** — a short or site-wrong CA HTTP list must
          not hide names that OpenVoxDB already has.
        - **DNS RR names only** are stripped (``ovca.corp``, ``ovdb.corp``).
          Real HAProxy boxes such as ``ovcompilers.*`` stay visible.

        Result is cached ~15s (single-flight) and copied so callers can
        mutate status overlays without poisoning the cache.
        """
        async def _build() -> List[Dict]:
            return await self._compute_live_nodes()

        cached = await cache_get_or_set("live_nodes:v1", 45.0, _build)
        return deepcopy(cached) if cached is not None else []

    async def _compute_live_nodes(self) -> List[Dict]:
        active = await self.get_nodes(include_inactive=False)
        try:
            from .cluster_config import fleet_excluded_certnames

            excluded = set(fleet_excluded_certnames())
        except Exception:
            excluded = set()

        try:
            from .dismissed_nodes import dismissed_certnames

            excluded |= await dismissed_certnames()
        except Exception:
            pass

        live = [
            n
            for n in active
            if str(n.get("certname", "")).strip().lower() not in excluded
        ]
        live.sort(key=lambda n: str(n.get("certname", "")).lower())
        if excluded:
            logger.debug(
                "get_live_nodes: excluded %d DNS-RR name(s)",
                len(excluded),
            )
        try:
            from ..config import settings
            from .fleet_insights import apply_report_freshness

            apply_report_freshness(
                live,
                failed_hours=float(getattr(settings, "failed_alert_hours", 8.0) or 0),
                fresh_hours=float(getattr(settings, "node_fresh_hours", 24.0) or 0),
            )
        except Exception:
            logger.debug("report freshness annotation skipped", exc_info=True)
        # Same live-run overlay Dashboard / Nodes / Monitoring already apply
        # so Heatmap, Environments, and Inventory cannot disagree.
        # Keep PDB status so Overview graphs stay identical across consoles.
        for n in live:
            if "pdb_latest_report_status" not in n:
                n["pdb_latest_report_status"] = n.get("latest_report_status")
        try:
            from ..database import async_session
            from ..routers.nodes import apply_live_run_status

            async with async_session() as db:
                await apply_live_run_status(live, db)
        except Exception:
            logger.debug("live-run overlay skipped", exc_info=True)
        return live

    async def get_fleet_nodes(self) -> List[Dict]:
        """Return signed CA certificates enriched with PuppetDB records.

        **Not** the membership SSoT for Overview | Nodes, Inventory, or ENC —
        those use ``get_live_nodes()`` (active PuppetDB). This CA union is
        for the Certificates page and callers that need every trusted cert
        (including signed certs that never reported to PuppetDB).

        - Starts from `puppetserver ca list --all` (signed certs).
        - Enriches every certname with its full PuppetDB record (if present),
          including deactivated/expired nodes (by calling get_nodes with include_inactive).
        - For signed certs that have never appeared in PuppetDB (newly signed,
          never bootstrapped, or long-term orphans not yet cleaned), returns a
          minimal "synthetic" NodeSummary entry with status=None (treated as
          "unreported").
        - Result is always exactly one entry per signed certname, sorted.
        """
        # Domain service (srdevarch1 HP3) — no router import / cycle.
        from .certificates_service import list_certificates as list_ca_certificates

        # Get the authoritative list of signed certs (the fleet)
        try:
            cert_data = await list_ca_certificates()
            signed_certs = cert_data.get("signed", []) if isinstance(cert_data, dict) else []
        except Exception as e:
            logger.warning(f"Failed to load CA signed cert list for fleet nodes: {e}", exc_info=True)
            signed_certs = []

        # Get the richest possible PDB data (active + deactivated + expired)
        # so we can attach status, last report, environment, etc. to matching certs.
        try:
            pdb_nodes = await self.get_nodes(include_inactive=True)
        except Exception as e:
            logger.warning(f"Failed to load full PDB nodes for fleet enrichment: {e}", exc_info=True)
            pdb_nodes = []

        pdb_map: dict[str, dict] = {}
        for n in pdb_nodes:
            k = str(n.get("certname", "")).strip().lower()
            if k:
                pdb_map[k] = n

        fleet: list[dict] = []
        seen: set[str] = set()
        for cert in signed_certs:
            cn = str(cert.get("name", "")).strip()
            k = cn.lower()
            if not cn or k in seen:
                continue
            seen.add(k)

            pdb = pdb_map.get(k)
            if pdb:
                entry = dict(pdb)  # copy the rich record
                # Ensure canonical certname casing from the CA (usually matches)
                entry["certname"] = cn
            else:
                # Signed cert with no PDB record at all → synthetic unreported entry.
                # These are the "lost" nodes that were not appearing on Dashboard/Nodes.
                entry = {
                    "certname": cn,
                    "latest_report_status": None,
                    "report_timestamp": None,
                    "catalog_timestamp": None,
                    "facts_timestamp": None,
                    "report_environment": None,
                    "latest_report_noop": None,
                    "latest_report_corrective_change": None,
                    "deactivated": None,
                    "expired": None,
                }
            fleet.append(entry)

        # Sort alphabetically (consistent with every other node list in the app)
        fleet.sort(key=lambda n: str(n.get("certname", "")).lower())
        return fleet

    async def get_node(self, certname: str) -> Dict:
        """Get a single node by certname, status overlaid from newest report."""
        result = None
        last_404: Optional[httpx.HTTPStatusError] = None
        for name in _cert_aliases(certname):
            try:
                result = await self._query(f"nodes/{name}")
                break
            except httpx.HTTPStatusError as e:
                if e.response.status_code == 404:
                    last_404 = e
                    continue
                raise
        if result is None:
            if last_404:
                raise last_404
            return {}
        if isinstance(result, dict):
            # Per-certname newest report is enough for one node. The fleet
            # overlay (latest_report? + 48h window + every peer) is the
            # bulk-list path; only use it when this node's query misses.
            newest = await self.get_newest_report_for_certname(certname)
            if newest and newest.get("status"):
                result["node_index_status"] = result.get("node_index_status") or result.get(
                    "latest_report_status"
                )
                result["latest_report_status"] = newest.get("status")
                ts = (
                    newest.get("end_time")
                    or newest.get("receive_time")
                    or newest.get("start_time")
                )
                if ts:
                    result["report_timestamp"] = ts
                result["latest_report_hash"] = newest.get("hash")
                result["cached_catalog_status"] = newest.get("cached_catalog_status")
                result["report_producer"] = newest.get("producer")
                result["status_source"] = "newest_report"
            else:
                await self._overlay_latest_report_status([result])
        return result

    async def _query_node_collection(self, kind: str, certname: str) -> List[Dict]:
        """facts or resources for one node.

        ``GET /nodes/<cert>/facts`` is 404 when the certname is unknown
        to this OpenVoxDB (ENC-only names, FQDN vs short certname). That
        is empty data, not a server error. Try aliases, then PQL (which
        returns [] instead of 404).
        """
        if kind not in ("facts", "resources"):
            raise ValueError(f"unsupported node collection: {kind}")
        aliases = _cert_aliases(certname)
        for name in aliases:
            try:
                rows = await self._query(f"nodes/{name}/{kind}")
            except httpx.HTTPStatusError as e:
                if e.response.status_code == 404:
                    continue
                raise
            if isinstance(rows, list):
                return rows
        for name in aliases:
            safe = name.replace("\\", "\\\\").replace('"', '\\"')
            try:
                rows = await self._query(
                    "",
                    params={"query": f'{kind} {{ certname = "{safe}" }}'},
                )
            except httpx.HTTPStatusError as e:
                if e.response.status_code == 404:
                    continue
                raise
            if isinstance(rows, list) and rows:
                return rows
        return []

    async def get_node_facts(self, certname: str) -> List[Dict]:
        """Get all facts for a node. Unknown certname → []."""
        return await self._query_node_collection("facts", certname)

    async def get_node_resources(self, certname: str) -> List[Dict]:
        """Get all resources for a node. Unknown certname → []."""
        return await self._query_node_collection("resources", certname)

    async def get_node_applied_classes(self, certname: str) -> List[str]:
        """Class titles from the last catalog (not ENC layers)."""
        import json

        ast = json.dumps([
            "extract", ["title"],
            ["and", ["=", "type", "Class"], ["=", "certname", certname]],
        ])
        rows: Any = None
        try:
            rows = await self._query("resources", query=ast)
        except Exception:
            try:
                safe = certname.replace("\\", "\\\\").replace('"', '\\"')
                rows = await self._query(
                    "",
                    params={
                        "query": (
                            f'resources[title] {{ type = "Class" and '
                            f'certname = "{safe}" }}'
                        )
                    },
                )
            except Exception:
                resources = await self.get_node_resources(certname) or []
                return sorted(
                    {
                        r.get("title")
                        for r in resources
                        if r.get("type") == "Class"
                        and r.get("title") not in ("main", "Settings")
                        and r.get("title")
                    }
                )
        titles = []
        if isinstance(rows, list):
            for r in rows:
                t = r.get("title") if isinstance(r, dict) else None
                if t and t not in ("main", "Settings"):
                    titles.append(t)
        return sorted(set(titles))

    async def get_node_resource_count(self, certname: str) -> int:
        """Catalog size without downloading every resource document."""
        safe = certname.replace("\\", "\\\\").replace('"', '\\"')
        try:
            rows = await self._query(
                "",
                params={"query": f'resources[count()]{{certname = "{safe}"}}'},
            )
            if isinstance(rows, list) and rows:
                row = rows[0]
                if isinstance(row, dict):
                    for v in row.values():
                        if isinstance(v, int):
                            return v
                        try:
                            return int(v)
                        except (TypeError, ValueError):
                            continue
        except Exception as e:
            logger.debug("resource count PQL failed for %s: %s", certname, e)
        try:
            resources = await self.get_node_resources(certname) or []
            return len(resources)
        except Exception:
            return 0

    async def deactivate_node(self, certname: str) -> bool:
        """Deactivate a node in PuppetDB via the command API.

        Sends a 'deactivate node' command directly to PuppetDB's
        /pdb/cmd/v1 endpoint using the existing mTLS connection.
        No sudo or CLI tools needed. Command is async on the PDB side —
        use wait_until_not_active() to verify the node drops out of
        active inventory lists.
        """
        from datetime import datetime, timezone

        client = await self._get_client()
        payload = {
            "command": "deactivate node",
            "version": 3,
            "payload": {
                "certname": certname,
                "producer_timestamp": datetime.now(timezone.utc).isoformat(),
            },
        }
        try:
            resp = await client.post("/pdb/cmd/v1", json=payload)
            resp.raise_for_status()
            logger.info(f"Deactivated node '{certname}' from PuppetDB via command API")
            return True
        except Exception as e:
            logger.warning(f"Failed to deactivate node '{certname}' via PuppetDB API: {e}", exc_info=True)
            return False

    async def is_node_active(self, certname: str) -> Optional[bool]:
        """
        Return True if certname is present as an *active* PuppetDB node,
        False if missing or deactivated/expired, None on query error.
        """
        try:
            key = (certname or "").strip().lower()
            if not key:
                return False
            # Membership only. Report overlay scans the fleet (latest_report?
            # plus a 48h window and every peer) and this method never reads
            # status. Deactivate polling calls this in a tight loop.
            nodes = await self.get_nodes(include_inactive=True, overlay_reports=False)
            for n in nodes:
                if str(n.get("certname", "")).strip().lower() != key:
                    continue
                if n.get("deactivated") or n.get("expired"):
                    return False
                return True
            return False
        except Exception as e:
            logger.warning(f"is_node_active({certname}): {e}")
            return None

    async def wait_until_not_active(
        self, certname: str, timeout_s: float = 20.0, interval_s: float = 0.75
    ) -> bool:
        """Poll until the node is not in the active PuppetDB set (or timeout)."""
        import time

        deadline = time.monotonic() + timeout_s
        while time.monotonic() < deadline:
            active = await self.is_node_active(certname)
            if active is False:
                return True
            await asyncio.sleep(interval_s)
        # Final check
        return (await self.is_node_active(certname)) is False

    # ─── Reports ────────────────────────────────────────────

    async def pql(self, query: str, limit: int = 5000) -> Any:
        """Run a PQL query against /pdb/query/v4 (no trailing slash)."""
        client = await self._get_client()
        resp = await client.get(
            "/pdb/query/v4",
            params={"query": query, "limit": str(limit)},
        )
        resp.raise_for_status()
        return resp.json()

    async def get_latest_reports_by_certname(self) -> Dict[str, Dict]:
        """One newest report document per certname.

        ``latest_report?`` is a hint only. OpenVoxDB (especially a
        multi-writer / Spock mesh) can leave that flag on an older
        ``failed`` row after a later successful report is stored. Always
        merge a recent ``receive_time`` window and keep the newest row
        per exact certname. Do not put ``order by`` in PQL text —
        OpenVoxDB rejects it.
        """
        out: Dict[str, Dict] = {}

        try:
            flagged = await self.pql(
                "reports[certname, status, receive_time, start_time, end_time, "
                "hash, producer, cached_catalog_status, noop] { latest_report? = true }",
                limit=5000,
            ) or []
            for row in flagged:
                _fold_newest_report(out, row)
        except Exception as e:
            logger.warning("PQL latest_report? failed, trying AST: %s", e)
            try:
                flagged = await self.get_reports(
                    query='["=", "latest_report?", true]',
                    limit=5000,
                ) or []
                for row in flagged:
                    _fold_newest_report(out, row)
            except Exception as e2:
                logger.warning("AST latest_report? failed: %s", e2)

        # Last 48h via AST extract (HTTP order_by). Replaces a stuck
        # latest_report? flag. Unbounded "newest 2000" can miss a node
        # that reported once while others flooded the window.
        try:
            from datetime import datetime, timedelta, timezone

            cutoff = (
                datetime.now(timezone.utc) - timedelta(hours=48)
            ).strftime("%Y-%m-%dT%H:%M:%S.000Z")
            recent = await self.get_reports_lean(
                query=f'[">", "receive_time", "{cutoff}"]',
                limit=10000,
                order_by="receive_time",
                order_dir="desc",
            ) or []
            for row in recent:
                _fold_newest_report(out, row)
        except Exception as e:
            logger.warning("recent reports window failed: %s", e)

        # Dual-VIP: this console's ovdb.example.com A record is one site.
        # Merge newest receive_time from configured peer OpenVoxDBs so
        # Overview / Needs attention match the other console.
        try:
            peers = self._peer_puppetdb_hosts()
        except Exception:
            peers = []
        if peers:
            peer_maps = await asyncio.gather(
                *[self._latest_reports_from_host(h) for h in peers],
                return_exceptions=True,
            )
            for host, result in zip(peers, peer_maps):
                if isinstance(result, Exception):
                    logger.warning(
                        "peer OpenVoxDB %s latest reports failed: %s",
                        host,
                        result,
                    )
                    continue
                for row in (result or {}).values():
                    if not isinstance(row, dict):
                        continue
                    copied = dict(row)
                    copied["_openvoxdb_source"] = host
                    _fold_newest_report(out, copied)

        return out

    async def get_newest_report_for_certname(self, certname: str) -> Optional[Dict]:
        """Newest report for one certname by receive_time (not the node index)."""
        # Exact certname only — do not query bare "ovca1" (collides across sites).
        # OpenVoxDB rejects PQL ``order by``; use the AST reports endpoint.
        cn = (certname or "").strip()
        if not cn:
            return None
        safe = cn.replace("\\", "").replace('"', "")
        try:
            rows = await self.get_reports(
                query=f'["=", "certname", "{safe}"]',
                limit=50,
                order_by="receive_time",
                order_dir="desc",
            ) or []
        except Exception as e:
            logger.warning("newest report query failed certname=%s: %s", cn, e)
            rows = []
        best: Optional[Dict] = None
        for row in rows:
            if not isinstance(row, dict):
                continue
            if best is None or _report_ts(row) >= _report_ts(best):
                best = row
        try:
            peers = self._peer_puppetdb_hosts()
        except Exception:
            peers = []
        for host in peers:
            try:
                remote = await self._query_host(
                    host,
                    "reports",
                    query=f'["=", "certname", "{safe}"]',
                    params={
                        "limit": "50",
                        "order_by": '[{"field": "receive_time", "order": "desc"}]',
                    },
                ) or []
            except Exception as e:
                logger.warning(
                    "peer OpenVoxDB %s newest report failed certname=%s: %s",
                    host,
                    cn,
                    e,
                )
                continue
            for row in remote:
                if not isinstance(row, dict):
                    continue
                if best is None or _report_ts(row) >= _report_ts(best):
                    best = dict(row)
                    best["_openvoxdb_source"] = host
        return best

    async def _overlay_latest_report_status(self, nodes: List[Dict]) -> None:
        """Set display status from the newest report document, not the node index.

        PuppetDB report ``status`` is failed/changed/unchanged. The node-index
        field and ``latest_report?`` can stick on failed after a later
        successful report exists — we overlay the newest ``receive_time``.
        """
        if not nodes:
            return
        latest = await self.get_latest_reports_by_certname()
        for node in nodes:
            key = str(node.get("certname") or "").strip().lower()
            node["node_index_status"] = node.get("latest_report_status")
            row = _pick_report_for_node(key, latest)
            if not row:
                node["status_source"] = "node_index"
                continue
            status = row.get("status")
            if status:
                prev = node.get("latest_report_status")
                if prev != status:
                    logger.info(
                        "overlay latest report status certname=%s node_index=%s latest_report=%s hash=%s",
                        node.get("certname"),
                        prev,
                        status,
                        row.get("hash"),
                    )
                node["latest_report_status"] = status
            ts = row.get("end_time") or row.get("receive_time") or row.get("start_time")
            if ts:
                node["report_timestamp"] = ts
            node["latest_report_hash"] = row.get("hash")
            node["cached_catalog_status"] = row.get("cached_catalog_status")
            node["report_producer"] = row.get("producer")
            node["status_source"] = "latest_report"

    async def get_reports(self, query: Optional[str] = None,
                          limit: int = 50, offset: int = 0,
                          order_by: str = "receive_time",
                          order_dir: str = "desc") -> List[Dict]:
        """Get reports from PuppetDB."""
        params = {
            "limit": str(limit),
            "offset": str(offset),
            "order_by": f'[{{"field": "{order_by}", "order": "{order_dir}"}}]',
        }
        return await self._query("reports", query=query, params=params)

    _LEAN_REPORT_FIELDS = (
        '["certname", "status", "noop", "receive_time", "hash", '
        '"producer", "cached_catalog_status", "start_time", "end_time", '
        '"corrective_change"]'
    )

    # List/detail summary tables. Still no logs, metrics, or resource_events.
    _SUMMARY_REPORT_FIELDS = (
        '["certname", "hash", "status", "environment", "noop", '
        '"puppet_version", "configuration_version", "corrective_change", '
        '"receive_time", "start_time", "end_time"]'
    )

    async def get_reports_lean(
        self,
        query: Optional[str] = None,
        limit: int = 2000,
        offset: int = 0,
        order_by: str = "receive_time",
        order_dir: str = "desc",
        fields: Optional[str] = None,
    ) -> List[Dict]:
        """Projected report rows — no metrics/logs/events payloads."""
        extract_fields = fields or self._LEAN_REPORT_FIELDS
        if query:
            ast = f'["extract", {extract_fields}, {query}]'
        else:
            ast = f'["extract", {extract_fields}]'
        params = {
            "limit": str(limit),
            "offset": str(offset),
            "order_by": f'[{{"field": "{order_by}", "order": "{order_dir}"}}]',
        }
        rows = await self._query("reports", query=ast, params=params)
        return _project_rows(rows, extract_fields)

    async def get_pdb_metrics_bulk(self, names: Dict[str, str]) -> Dict[str, Any]:
        """One Jolokia POST for many mbeans. Fallback: per-bean GET."""
        out: Dict[str, Any] = {k: None for k in names}
        if not names:
            return out
        try:
            client = await self._get_client()
            # POST body uses real ObjectNames. !/ is only for GET URL paths.
            body = [
                {"type": "read", "mbean": unescape_jolokia_mbean(mbean)}
                for mbean in names.values()
            ]
            resp = await client.post("/metrics/v2/read", json=body)
            if resp.status_code == 200:
                payload = resp.json()
                rows = payload if isinstance(payload, list) else (
                    payload.get("value") if isinstance(payload, dict) else None
                )
                by_mbean: Dict[str, Any] = {}
                if isinstance(rows, list):
                    for row in rows:
                        if not isinstance(row, dict):
                            continue
                        req = row.get("request") or {}
                        mbean = req.get("mbean")
                        val = jolokia_row_value(row)
                        if mbean and val is not None:
                            by_mbean[normalize_mbean(str(mbean))] = val
                for key, mbean in names.items():
                    matched = by_mbean.get(normalize_mbean(mbean))
                    if matched is not None:
                        out[key] = matched
        except Exception as e:
            logger.warning("Jolokia bulk read failed: %s", e)
        missing = {k: m for k, m in names.items() if out.get(k) is None}
        if missing:
            async def _one(key: str, mbean: str) -> None:
                out[key] = (await self.get_pdb_metrics(mbean)).get("value")
            await asyncio.gather(*[_one(k, m) for k, m in missing.items()])
        return out

    async def get_report(self, report_hash: str) -> Dict:
        """Get a single report by hash (exact, then unique prefix).

        OpenVoxDB stores SHA-256 (64 hex). Older PuppetDB used SHA-1 (40).
        Operators and some UIs paste a prefix. Exact ``=`` misses those.
        On a clustered estate the ATLC console's OpenVoxDB may not have
        a PDXC-originated row yet — try configured peer OpenVoxDB hosts.
        """
        h = _validate_report_hash(report_hash)
        found = await self._lookup_report(h)
        if found:
            return found
        for peer in self._peer_puppetdb_hosts():
            try:
                found = await self._lookup_report_on_host(peer, h)
            except Exception as e:
                logger.warning("peer OpenVoxDB %s report lookup failed: %s", peer, e)
                continue
            if found:
                found["_openvoxdb_source"] = peer
                logger.info("report %s found on peer OpenVoxDB %s", h, peer)
                return found
        return {}

    def _peer_puppetdb_hosts(self) -> List[str]:
        try:
            from .cluster_config import load_cluster_config
            cfg = load_cluster_config()
        except Exception:
            cfg = {}
        primary = (settings.puppetdb_host or "").strip().lower()
        out: List[str] = []

        def _add(host: str) -> None:
            h = (host or "").strip().lower()
            if h and h != primary and h not in out:
                out.append(h)

        extra = getattr(settings, "puppetdb_peers", None) or ""
        for part in str(extra).replace(",", " ").split():
            _add(part)
        # Every configured OpenVoxDB member — VIP DNS RR can land on
        # different replicas; newest receive_time across members wins.
        for host in cfg.get("puppetdb_nodes") or []:
            _add(str(host))
        return out

    async def _query_host(
        self,
        host: str,
        endpoint: str,
        query: Optional[str] = None,
        params: Optional[Dict] = None,
    ) -> Any:
        """PuppetDB v4 query against an explicit peer FQDN."""
        port = settings.puppetdb_port
        if endpoint:
            url = f"https://{host}:{port}/pdb/query/v4/{endpoint}".rstrip("/")
        else:
            url = f"https://{host}:{port}/pdb/query/v4"
        request_params = dict(params or {})
        if query:
            request_params["query"] = query
        ctx = self._create_ssl_context()
        async with httpx.AsyncClient(
            verify=ctx,
            timeout=httpx.Timeout(4.0, connect=2.0),
            trust_env=False,
        ) as client:
            resp = await client.get(url, params=request_params)
            resp.raise_for_status()
            return resp.json()

    async def _latest_reports_from_host(self, host: str) -> Dict[str, Dict]:
        """Newest report per certname on one peer OpenVoxDB."""
        out: Dict[str, Dict] = {}
        pql = (
            "reports[certname, status, receive_time, start_time, end_time, "
            "hash, producer, cached_catalog_status, noop] { latest_report? = true }"
        )
        try:
            flagged = await self._query_host(
                host, "", query=pql, params={"limit": "5000"}
            ) or []
            for row in flagged:
                _fold_newest_report(out, row)
        except Exception as e:
            logger.warning("peer %s latest_report? failed: %s", host, e)
        # Same 48h projected window as the primary. A bare reports query
        # returns full documents (logs, metrics, events) — up to 2000 of
        # them per peer on every live-fleet rebuild.
        try:
            from datetime import datetime, timedelta, timezone

            cutoff = (
                datetime.now(timezone.utc) - timedelta(hours=48)
            ).strftime("%Y-%m-%dT%H:%M:%S.000Z")
            window = f'[">", "receive_time", "{cutoff}"]'
            ast = f'["extract", {self._LEAN_REPORT_FIELDS}, {window}]'
            recent = await self._query_host(
                host,
                "reports",
                query=ast,
                params={
                    "limit": "10000",
                    "order_by": '[{"field": "receive_time", "order": "desc"}]',
                },
            ) or []
            for row in _project_rows(recent, self._LEAN_REPORT_FIELDS):
                _fold_newest_report(out, row)
        except Exception as e:
            logger.warning(
                "peer %s lean recent reports failed (%s); falling back to full rows",
                host,
                e,
            )
            try:
                recent = await self._query_host(
                    host,
                    "reports",
                    params={
                        "limit": "2000",
                        "order_by": '[{"field": "receive_time", "order": "desc"}]',
                    },
                ) or []
                for row in recent:
                    _fold_newest_report(out, row)
            except Exception as e2:
                logger.warning("peer %s recent reports failed: %s", host, e2)
        return out

    async def _lookup_report(self, h: str) -> Dict:
        """Exact, then prefix, then PQL — against the primary OpenVoxDB."""
        results = await self._query(
            "reports",
            query=f'["=", "hash", "{h}"]',
        )
        if results:
            return results[0] if isinstance(results[0], dict) else {}
        if len(h) < 64:
            try:
                prefixed = await self.get_reports(
                    query=f'["~", "hash", "^{h}"]',
                    limit=20,
                    order_by="receive_time",
                    order_dir="desc",
                ) or []
                if prefixed and isinstance(prefixed[0], dict):
                    return prefixed[0]
            except Exception as e:
                logger.warning("prefix report lookup failed hash=%s: %s", h, e)
            try:
                rows = await self.pql(f'reports {{ hash ~ "^{h}" }}', limit=20) or []
                if rows and isinstance(rows[0], dict):
                    return rows[0]
            except Exception as e:
                logger.warning("PQL prefix report lookup failed hash=%s: %s", h, e)
        return {}

    async def _lookup_report_on_host(self, host: str, h: str) -> Dict:
        """Same lookup against a peer OpenVoxDB FQDN (clustered)."""
        url = f"https://{host}:{settings.puppetdb_port}/pdb/query/v4/reports"
        ctx = self._create_ssl_context()
        queries = [f'["=", "hash", "{h}"]']
        if len(h) < 64:
            queries.append(f'["~", "hash", "^{h}"]')
        async with httpx.AsyncClient(
            verify=ctx,
            timeout=httpx.Timeout(10.0, connect=4.0),
            trust_env=False,
        ) as client:
            for q in queries:
                resp = await client.get(
                    url,
                    params={
                        "query": q,
                        "limit": "20",
                        "order_by": '[{"field": "receive_time", "order": "desc"}]',
                    },
                )
                if resp.status_code >= 400:
                    continue
                rows = resp.json() or []
                if rows and isinstance(rows[0], dict):
                    return rows[0]
        return {}

    async def get_report_events(self, report_hash: str) -> List[Dict]:
        """Get resource events for a specific report.

        The hash is validated before PQL interpolation.
        """
        report_hash = _validate_report_hash(report_hash)
        return await self._query(
            "events",
            query=f'["=", "report", "{report_hash}"]'
        )

    async def get_report_logs(self, report_hash: str) -> List[Dict]:
        """Get logs for a specific report from PuppetDB's sub-endpoint.

        The hash is validated before being used in the URL path. Returns
        an empty list on failure rather than raising, because log retrieval
        is supplementary to the main report data.
        """
        report_hash = _validate_report_hash(report_hash)
        try:
            return await self._query(f"reports/{report_hash}/logs")
        except Exception as e:
            logger.warning(f"Failed to fetch logs for report {report_hash}: {e}", exc_info=True)
            return []

    async def get_report_metrics(self, report_hash: str) -> List[Dict]:
        """Get metrics for a specific report from PuppetDB's sub-endpoint.

        The hash is validated before being used in the URL path. Returns
        an empty list on failure for the same reason as get_report_logs.
        """
        report_hash = _validate_report_hash(report_hash)
        try:
            return await self._query(f"reports/{report_hash}/metrics")
        except Exception as e:
            logger.warning(f"Failed to fetch metrics for report {report_hash}: {e}", exc_info=True)
            return []

    # ─── Facts ──────────────────────────────────────────────

    async def get_facts(self, fact_name: Optional[str] = None,
                        query: Optional[str] = None) -> List[Dict]:
        """Get facts, optionally filtered by name."""
        endpoint = f"facts/{fact_name}" if fact_name else "facts"
        return await self._query(endpoint, query=query)

    async def get_fact_contents(self, path: List[str]) -> List[Dict]:
        """Structured-fact leaves via /fact-contents (path = ['os', 'family'])."""
        import json

        query = json.dumps(["=", "path", list(path)])
        data = await self._query("fact-contents", query=query)
        return data if isinstance(data, list) else []

    async def get_fact_names(self) -> List[str]:
        """Get all known fact names."""
        return await self._query("fact-names")

    # ─── Environments ───────────────────────────────────────

    async def get_environments(self) -> List[Dict]:
        """Get all environments from PuppetDB."""
        return await self._query("environments")

    # ─── Metrics / Dashboard ────────────────────────────────

    async def get_node_status_counts(self) -> Dict[str, int]:
        """Get node status distribution."""
        nodes = await self.get_nodes()
        counts = {"changed": 0, "unchanged": 0, "failed": 0,
                  "unreported": 0, "noop": 0, "total": len(nodes)}
        for node in nodes:
            status = node.get("latest_report_status")
            if node.get("latest_report_noop"):
                counts["noop"] += 1
            elif status in counts:
                counts[status] += 1
            elif status is None:
                counts["unreported"] += 1
            else:
                counts["unchanged"] += 1
        return counts

    async def get_report_trends(self, hours: int = 24) -> List[Dict]:
        """Get report status trends over time."""
        from datetime import datetime, timezone, timedelta
        cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).strftime(
            "%Y-%m-%dT%H:%M:%S.000Z"
        )
        reports = await self._query(
            "reports",
            query=f'[">" , "receive_time", "{cutoff}"]',
            params={
                "limit": "20000",
                "order_by": '[{"field": "receive_time", "order": "desc"}]'
            }
        )
        # Bucket by hour
        from collections import defaultdict
        buckets = defaultdict(lambda: {"changed": 0, "unchanged": 0, "failed": 0})
        for report in reports:
            ts = report.get("receive_time", "")[:13]  # YYYY-MM-DDTHH
            status = report.get("status", "unchanged")
            if status in buckets[ts]:
                buckets[ts][status] += 1

        return [
            {"timestamp": k, "changed": v["changed"],
             "unchanged": v["unchanged"], "failed": v["failed"]}
            for k, v in sorted(buckets.items())
        ][-48:]  # Last 48 data points

    async def get_node_status_trends(self) -> List[Dict]:
        """Get node status trends over time (bucketed by hour from reports).

        Uses a rolling-state model so every hour bucket reflects the full
        fleet, matching the donut chart.  Each node carries its last known
        status forward until a new report updates it.  Nodes that have
        genuinely never reported show as 'unreported'.
        """
        from collections import defaultdict
        from datetime import datetime, timezone, timedelta

        cutoff = (datetime.now(timezone.utc) - timedelta(hours=48)).strftime(
            "%Y-%m-%dT%H:%M:%S.000Z"
        )
        nodes, reports = await asyncio.gather(
            self.get_nodes(),
            self._query(
                "reports",
                query=f'[">" , "receive_time", "{cutoff}"]',
                params={
                    "limit": "20000",
                    "order_by": '[{"field": "receive_time", "order": "asc"}]'
                }
            ),
        )

        # Seed each node's status from PuppetDB's current record.
        # This covers nodes whose last report predates the 48h window.
        node_state: Dict[str, str] = {}
        for n in nodes:
            cn = n.get("certname", "")
            if not cn:
                continue
            if n.get("latest_report_noop"):
                node_state[cn] = "noop"
            elif n.get("latest_report_status"):
                node_state[cn] = n["latest_report_status"]
            else:
                node_state[cn] = "unreported"

        # Group reports by hour bucket (already sorted ascending)
        bucket_reports: Dict[str, list] = defaultdict(list)
        for report in reports:
            ts = report.get("receive_time", "")[:13]  # YYYY-MM-DDTHH
            bucket_reports[ts].append(report)

        all_buckets = sorted(bucket_reports.keys())
        if not all_buckets:
            return []

        result = []
        for bucket in all_buckets:
            # Apply every report in this hour, updating rolling state
            for report in bucket_reports[bucket]:
                cn = report.get("certname", "")
                if cn not in node_state:
                    continue
                if report.get("noop", False):
                    node_state[cn] = "noop"
                else:
                    node_state[cn] = report.get("status", "unchanged")

            # Snapshot the full fleet
            counts = {"unchanged": 0, "changed": 0, "failed": 0,
                      "noop": 0, "unreported": 0}
            for status in node_state.values():
                if status in counts:
                    counts[status] += 1
                else:
                    counts["unchanged"] += 1

            result.append({"timestamp": bucket, **counts})

        return result[-48:]

    async def get_aggregate_event_counts(self) -> Dict:
        """Get aggregate event counts."""
        try:
            result = await self._query(
                "aggregate-event-counts",
                params={"summarize_by": "certname"}
            )
            return result
        except Exception:
            return {}

    async def get_server_time(self) -> Optional[str]:
        """Get PuppetDB server time."""
        try:
            result = await self._query("server-time")
            return result.get("server_time")
        except Exception:
            return None


    # ─── Events (fleet-wide) ─────────────────────────────────

    async def get_events(self, query: Optional[str] = None,
                         limit: int = 500) -> List[Dict]:
        """Get resource events across all nodes."""
        params = {
            "limit": str(limit),
            "order_by": '[{"field": "timestamp", "order": "desc"}]',
        }
        return await self._query("events", query=query, params=params)

    # ─── Catalogs ────────────────────────────────────────────

    async def get_catalog_edges(self, certname: str) -> List[Dict]:
        """Get dependency edges from a node's compiled catalog via PQL."""
        client = await self._get_client()
        query = f'edges {{ certname = "{certname}" }}'
        resp = await client.get("/pdb/query/v4", params={"query": query})
        resp.raise_for_status()
        raw = resp.json()
        # PQL edges return flat fields; normalize to source/target dicts
        edges = []
        for e in raw:
            edges.append({
                "source": {"type": e.get("source_type"), "title": e.get("source_title")},
                "target": {"type": e.get("target_type"), "title": e.get("target_title")},
                "relationship": e.get("relationship"),
            })
        return edges

    async def get_catalog_resources(self, certname: str) -> List[Dict]:
        """Get resources from a node's compiled catalog via PQL."""
        client = await self._get_client()
        query = f'resources {{ certname = "{certname}" }}'
        resp = await client.get("/pdb/query/v4", params={"query": query})
        resp.raise_for_status()
        return resp.json()

    # ─── PuppetDB Health ─────────────────────────────────────

    async def get_pdb_status(self) -> Dict:
        """Query PuppetDB's status endpoint for health info."""
        try:
            client = await self._get_client()
            resp = await client.get("/status/v1/services/puppetdb-status")
            resp.raise_for_status()
            return resp.json()
        except Exception as e:
            logger.warning(f"Failed to get PuppetDB status: {e}", exc_info=True)
            return {}

    async def get_remote_health(self) -> Dict[str, Any]:
        """PDB health via /status/v1/simple (VIP or localhost)."""
        host = settings.puppetdb_host
        try:
            client = await self._get_client()
            resp = await client.get("/status/v1/simple")
            text = (resp.text or "").strip().strip('"')
            if resp.status_code == 200 and text:
                out: Dict[str, Any] = {
                    "service": "puppetdb",
                    "status": "active" if text.lower() == "running" else text,
                    "source": "http",
                    "host": host,
                    "simple": text,
                }
                try:
                    ver = await client.get("/pdb/meta/v1/version")
                    if ver.status_code == 200:
                        body = ver.json()
                        if isinstance(body, dict) and body.get("version"):
                            out["version"] = str(body["version"])
                except Exception:
                    pass
                return out
            err = f"HTTP {resp.status_code}: {text[:200]}"
        except Exception as e:
            err = str(e)
            logger.warning("PuppetDB status HTTP failed: %s", e)
        return {
            "service": "puppetdb",
            "status": "unknown",
            "source": "http",
            "host": host,
            "error": err,
        }

    async def fetch_version(self) -> Optional[str]:
        try:
            client = await self._get_client()
            resp = await client.get("/pdb/meta/v1/version")
            if resp.status_code == 200:
                body = resp.json()
                if isinstance(body, dict) and body.get("version"):
                    return str(body["version"])
        except Exception as e:
            logger.debug("PuppetDB version HTTP failed: %s", e)
        return None

    async def get_pdb_metrics(self, metric_name: str) -> Dict:
        """Query PuppetDB's JMX metrics endpoint."""
        try:
            client = await self._get_client()
            resp = await client.get(f"/metrics/v2/read/{escape_jolokia_path(metric_name)}")
            resp.raise_for_status()
            body = resp.json()
            if isinstance(body, dict) and jolokia_row_value(body) is None and body.get("error"):
                return {}
            return body if isinstance(body, dict) else {}
        except Exception as e:
            logger.warning(f"Failed to get PuppetDB metric {metric_name}: {e}", exc_info=True)
            return {}

    async def search_pdb_mbeans(self, pattern: str) -> List[str]:
        """Jolokia search. *pattern* is an ObjectName glob, e.g. domain:name=*."""
        try:
            client = await self._get_client()
            resp = await client.get(f"/metrics/v2/search/{escape_jolokia_path(pattern)}")
            if resp.status_code != 200:
                return []
            body = resp.json()
            val = body.get("value") if isinstance(body, dict) else body
            if isinstance(val, list):
                return [str(x) for x in val if x]
            return []
        except Exception as e:
            logger.warning("Jolokia search failed for %s: %s", pattern, e)
            return []

    async def fill_pdb_http_latency(self, results: Dict[str, Any]) -> Dict[str, Any]:
        """Resolve query/cmd HTTP timers when the canned ObjectNames 404."""
        if timer_present(results.get("http_query_time")) and timer_present(
            results.get("http_cmd_time")
        ):
            return results
        beans = await self.search_pdb_mbeans("puppetlabs.puppetdb.http:name=*")
        query_name, cmd_name = pick_http_latency_beans(beans)
        to_fetch: Dict[str, str] = {}
        if not timer_present(results.get("http_query_time")) and query_name:
            to_fetch["http_query_time"] = query_name
        if not timer_present(results.get("http_cmd_time")) and cmd_name:
            to_fetch["http_cmd_time"] = cmd_name
        if to_fetch:
            extra = await self.get_pdb_metrics_bulk(to_fetch)
            for key, val in extra.items():
                if timer_present(val):
                    results[key] = val
        return results

    async def fill_pdb_storage_metrics(self, results: Dict[str, Any]) -> Dict[str, Any]:
        """Resolve storage timers when the unprefixed ObjectName is missing."""
        wanted = {
            "store_catalog": "replace-catalog-time",
            "store_facts": "replace-facts-time",
            "store_report": "store-report-time",
            "catalog_hash_match": "catalog-hash-match-time",
            "catalog_hash_miss": "catalog-hash-miss-time",
            "dedup_pct": "duplicate-pct",
        }
        if all(results.get(k) is not None for k in wanted):
            return results
        beans = await self.search_pdb_mbeans("puppetlabs.puppetdb.storage:name=*")
        to_fetch: Dict[str, str] = {}
        for key, suffix in wanted.items():
            if results.get(key) is not None:
                continue
            hit = next((b for b in beans if suffix in b), None)
            if hit:
                to_fetch[key] = hit
        if to_fetch:
            extra = await self.get_pdb_metrics_bulk(to_fetch)
            for key, val in extra.items():
                if val is not None:
                    results[key] = val
        return results

    # ─── System Inventory Report ────────────────────────────

    async def get_system_inventory(self) -> List[Dict]:
        """
        Live fleet-wide system inventory report.

        Membership is **active PuppetDB nodes only** (not deactivated / not
        expired) — the same set as ``get_nodes()`` / Overview | Nodes. PuppetDB
        retains factsets for deactivated and expired nodes until GC, so the
        raw ``inventory`` endpoint over-counts vs. the real fleet; we intersect
        with active nodes so Insights | Inventory matches the Nodes list.

        Fact payload still comes from the inventory endpoint (certname + full
        structured facts). Missing facts are empty strings for UI robustness.
        Disks are pre-formatted as newline-separated "name: size" strings.
        """
        # Membership only — skip report overlay / peer PDB merge (that is
        # for Overview badges). Inventory is facts, not run status.
        members = await self.get_nodes(overlay_reports=False)
        active_keys = {
            str(n.get("certname", "")).strip().lower()
            for n in members
            if n.get("certname")
        }

        # Full current facts for nodes that have reported factsets.
        # Response items: "certname" + "facts": { ... }.
        raw = await self._query("inventory") or []

        results: List[Dict] = []
        for item in raw:
            certname = item.get("certname", "") or ""
            key = certname.strip().lower()
            if not key or key not in active_keys:
                continue
            facts = item.get("facts") or {}

            # OS
            os_block = facts.get("os") or {}
            os_name = ""
            os_full = ""
            if isinstance(os_block, dict):
                os_name = os_block.get("name") or ""
                rel = os_block.get("release") or {}
                if isinstance(rel, dict):
                    os_full = rel.get("full") or ""
                elif isinstance(rel, str):
                    os_full = rel

            # Physical processors (prefer physicalcount)
            proc = facts.get("processors") or {}
            phys_cpus = ""
            if isinstance(proc, dict):
                phys_cpus = proc.get("physicalcount") or proc.get("count") or ""
            else:
                # In case projection flattened (defensive)
                phys_cpus = facts.get("processors.physicalcount") or facts.get("processors.count") or ""

            # Location (custom fact users often drop via facts.d or external fact)
            location = facts.get("location") or ""

            # Memory (human string preferred)
            mem_block = facts.get("memory") or {}
            memory = ""
            if isinstance(mem_block, dict):
                sysmem = mem_block.get("system") or {}
                if isinstance(sysmem, dict):
                    memory = sysmem.get("total") or ""
                else:
                    memory = mem_block.get("system.total") or ""
            else:
                memory = facts.get("memory.system.total") or ""

            # Disks: dict name -> info; format one "name: size" per line
            disks_block = facts.get("disks") or {}
            disk_lines: List[str] = []
            if isinstance(disks_block, dict):
                for dname in sorted(disks_block.keys()):
                    dinfo = disks_block[dname]
                    if isinstance(dinfo, dict):
                        size = dinfo.get("size") or dinfo.get("size_bytes") or "?"
                        disk_lines.append(f"{dname}: {size}")
                    else:
                        disk_lines.append(f"{dname}: {dinfo}")
            disks = "\n".join(disk_lines)

            # Virtual vs Physical
            # Leverage standard Facter facts: is_virtual (boolean or string) and virtual (type or "physical").
            # This is the authoritative source for "whether a virtual or physical system".
            # See: https://puppet.com/docs/puppet/latest/facter.html (is_virtual / virtual facts)
            is_virt = facts.get("is_virtual")
            virt_val = facts.get("virtual")

            # Normalize is_virtual to boolean (handles bool, "true", "1", "yes", etc.)
            if isinstance(is_virt, bool):
                is_virt_bool = is_virt
            elif isinstance(is_virt, (str, int)):
                is_virt_bool = str(is_virt).strip().lower() in ("true", "1", "yes")
            else:
                is_virt_bool = False

            if is_virt_bool:
                if isinstance(virt_val, str) and virt_val.strip():
                    v = virt_val.strip()
                    if v.lower() not in ("physical", "true", "1"):
                        vlabel = f"Virtual ({v})"
                    else:
                        vlabel = "Virtual"
                else:
                    vlabel = "Virtual"
            else:
                # Fallback to the virtual fact itself (common when is_virtual is false or absent)
                if isinstance(virt_val, str) and virt_val.strip():
                    v = virt_val.strip()
                    if v.lower() not in ("physical", "false", "0", ""):
                        vlabel = f"Virtual ({v})"
                    else:
                        vlabel = "Physical"
                else:
                    vlabel = "Physical"

            # Uptime (prefer the human 'uptime' string)
            up_block = facts.get("system_uptime") or {}
            uptime = ""
            if isinstance(up_block, dict):
                uptime = up_block.get("uptime") or ""
            if not uptime:
                uptime = facts.get("uptime") or facts.get("system_uptime.uptime") or ""

            results.append({
                "certname": certname,
                "os_name": os_name,
                "os_full_release": os_full,
                "physical_processors": phys_cpus,
                "location": location,
                "memory": memory,
                "disks": disks,
                "virtual_physical": vlabel,
                "uptime": uptime,
            })

        # Stable sort by certname (case-insensitive) like other lists
        results.sort(key=lambda r: (r.get("certname") or "").lower())
        return results


# Singleton
puppetdb_service = PuppetDBService()
