"""
PuppetDB API client service.

Provides an async HTTP client for communicating with PuppetDB's v4 REST
API over mutual-TLS (using the Puppet agent's SSL certificate and key).
This is the sole gateway for all PuppetDB queries in the application —
every router that needs PuppetDB data goes through the singleton
puppetdb_service instance defined at the bottom of this module.

The client is lazily initialised on first use and reused for the lifetime
of the process. Connection failures are logged and re-raised so that
callers (routers) can return appropriate HTTP error responses.

Security note: several methods accept a report_hash parameter that gets
interpolated into PQL query strings. Report hashes are hex strings
generated by PuppetDB, but because they arrive as user-supplied URL path
parameters, they are validated with a strict hex-only regex before
interpolation to prevent PQL injection.
"""
import asyncio
import re
import httpx
import ssl
import logging
from typing import Any, Dict, List, Optional
from ..config import settings

logger = logging.getLogger(__name__)

# PuppetDB report hashes are SHA-256 hex digests (64 lowercase hex chars).
# This strict pattern prevents PQL injection through crafted hash values
# passed in from URL path parameters.
_SAFE_HEX_HASH = re.compile(r'^[a-f0-9]+$')


def _validate_report_hash(report_hash: str) -> str:
    """Validate that a report hash is a safe hex string for use in PQL.

    PuppetDB report hashes are SHA-256 hex digests, so they should only
    contain lowercase hex characters (a-f, 0-9). Rejecting anything else
    prevents PQL injection through crafted hash values like:
        'abc123"] or true --'
    """
    if not report_hash or not _SAFE_HEX_HASH.match(report_hash):
        raise ValueError(f"Invalid report hash: must be a hex string")
    return report_hash


class PuppetDBService:
    """Async client for PuppetDB v4 API."""

    def __init__(self):
        self.base_url = f"https://{settings.puppetdb_host}:{settings.puppetdb_port}"
        self._client: Optional[httpx.AsyncClient] = None

    def _create_ssl_context(self) -> ssl.SSLContext:
        ctx = ssl.create_default_context(cafile=settings.puppet_ssl_ca)
        ctx.load_cert_chain(
            certfile=settings.puppet_ssl_cert,
            keyfile=settings.puppet_ssl_key,
        )
        return ctx

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                base_url=self.base_url,
                verify=self._create_ssl_context(),
                timeout=30.0,
            )
        return self._client

    async def close(self):
        if self._client and not self._client.is_closed:
            await self._client.aclose()

    async def _query(self, endpoint: str, query: Optional[str] = None,
                     params: Optional[Dict] = None) -> Any:
        """Execute a PuppetDB query.

        When endpoint is empty, this sends a PQL query to the base
        /pdb/query/v4 endpoint (no trailing slash — PuppetDB returns
        404 for the trailing-slash variant).
        """
        client = await self._get_client()
        url = f"/pdb/query/v4/{endpoint}".rstrip("/")
        request_params = params or {}
        if query:
            request_params["query"] = query
        try:
            resp = await client.get(url, params=request_params)
            resp.raise_for_status()
            return resp.json()
        except httpx.HTTPStatusError as e:
            logger.error(f"PuppetDB HTTP error: {e.response.status_code} - {e.response.text}")
            raise
        except Exception as e:
            logger.error(f"PuppetDB connection error: {e}")
            raise

    # ─── Nodes ──────────────────────────────────────────────

    async def get_nodes(self, query: Optional[str] = None,
                        include_inactive: bool = False) -> List[Dict]:
        """Get nodes from PuppetDB.

        By default, only returns active nodes (not deactivated or expired)
        and deduplicates by certname. PuppetDB retains deactivated/expired
        node records until they are purged, so filtering is essential to
        avoid displaying ghost nodes that have been removed from the Puppet
        CA but not yet purged from PuppetDB.

        Filtering is done in Python after fetch to guarantee correctness
        regardless of PuppetDB version or PQL operator support.
        """
        all_nodes = await self._query("nodes", query=query)

        if not include_inactive:
            all_nodes = [
                n for n in all_nodes
                if not n.get("deactivated") and not n.get("expired")
            ]

        # Deduplicate by certname (case-insensitive, stripped)
        seen: set = set()
        unique = []
        for node in all_nodes:
            key = node.get("certname", "").strip().lower()
            if key and key not in seen:
                seen.add(key)
                unique.append(node)
        return unique

    async def get_node(self, certname: str) -> Dict:
        """Get a single node by certname."""
        result = await self._query(f"nodes/{certname}")
        return result

    async def get_node_facts(self, certname: str) -> List[Dict]:
        """Get all facts for a node."""
        return await self._query(f"nodes/{certname}/facts")

    async def get_node_resources(self, certname: str) -> List[Dict]:
        """Get all resources for a node."""
        return await self._query(f"nodes/{certname}/resources")

    async def deactivate_node(self, certname: str) -> bool:
        """Deactivate a node in PuppetDB via the puppet CLI.

        This marks the node as deactivated so it no longer appears in
        active node queries. PuppetDB will eventually purge the node
        data based on its node-purge-ttl setting.
        """
        from ..utils.sudo import run_sudo

        result = await run_sudo(
            ["sudo", "/opt/puppetlabs/bin/puppet", "node", "deactivate", certname],
            timeout=30,
        )
        if result["returncode"] == 0:
            logger.info(f"Deactivated node '{certname}' from PuppetDB")
            return True
        logger.warning(
            f"Failed to deactivate node '{certname}': "
            f"rc={result['returncode']} stderr={result['stderr']}"
        )
        return False

    # ─── Reports ────────────────────────────────────────────

    async def get_reports(self, query: Optional[str] = None,
                          limit: int = 50, offset: int = 0,
                          order_by: str = "receive_time",
                          order_dir: str = "desc") -> List[Dict]:
        """Get reports from PuppetDB."""
        params = {
            "limit": str(limit),
            "offset": str(offset),
            "order_by": f'[{{"field": "{order_by}", "order": "{order_dir}"}}]',
        }
        return await self._query("reports", query=query, params=params)

    async def get_report(self, report_hash: str) -> Dict:
        """Get a single report by its SHA-256 hash.

        The hash is validated to contain only hex characters before being
        interpolated into the PQL query to prevent injection attacks.
        """
        report_hash = _validate_report_hash(report_hash)
        results = await self._query(
            "reports",
            query=f'["=", "hash", "{report_hash}"]'
        )
        if results:
            return results[0]
        return {}

    async def get_report_events(self, report_hash: str) -> List[Dict]:
        """Get resource events for a specific report.

        The hash is validated before PQL interpolation.
        """
        report_hash = _validate_report_hash(report_hash)
        return await self._query(
            "events",
            query=f'["=", "report", "{report_hash}"]'
        )

    async def get_report_logs(self, report_hash: str) -> List[Dict]:
        """Get logs for a specific report from PuppetDB's sub-endpoint.

        The hash is validated before being used in the URL path. Returns
        an empty list on failure rather than raising, because log retrieval
        is supplementary to the main report data.
        """
        report_hash = _validate_report_hash(report_hash)
        try:
            return await self._query(f"reports/{report_hash}/logs")
        except Exception as e:
            logger.warning(f"Failed to fetch logs for report {report_hash}: {e}")
            return []

    async def get_report_metrics(self, report_hash: str) -> List[Dict]:
        """Get metrics for a specific report from PuppetDB's sub-endpoint.

        The hash is validated before being used in the URL path. Returns
        an empty list on failure for the same reason as get_report_logs.
        """
        report_hash = _validate_report_hash(report_hash)
        try:
            return await self._query(f"reports/{report_hash}/metrics")
        except Exception as e:
            logger.warning(f"Failed to fetch metrics for report {report_hash}: {e}")
            return []

    # ─── Facts ──────────────────────────────────────────────

    async def get_facts(self, fact_name: Optional[str] = None,
                        query: Optional[str] = None) -> List[Dict]:
        """Get facts, optionally filtered by name."""
        endpoint = f"facts/{fact_name}" if fact_name else "facts"
        return await self._query(endpoint, query=query)

    async def get_fact_names(self) -> List[str]:
        """Get all known fact names."""
        return await self._query("fact-names")

    # ─── Environments ───────────────────────────────────────

    async def get_environments(self) -> List[Dict]:
        """Get all environments from PuppetDB."""
        return await self._query("environments")

    # ─── Metrics / Dashboard ────────────────────────────────

    async def get_node_status_counts(self) -> Dict[str, int]:
        """Get node status distribution."""
        nodes = await self.get_nodes()
        counts = {"changed": 0, "unchanged": 0, "failed": 0,
                  "unreported": 0, "noop": 0, "total": len(nodes)}
        for node in nodes:
            status = node.get("latest_report_status")
            if node.get("latest_report_noop"):
                counts["noop"] += 1
            elif status in counts:
                counts[status] += 1
            elif status is None:
                counts["unreported"] += 1
            else:
                counts["unchanged"] += 1
        return counts

    async def get_report_trends(self, hours: int = 24) -> List[Dict]:
        """Get report status trends over time."""
        from datetime import datetime, timezone, timedelta
        cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).strftime(
            "%Y-%m-%dT%H:%M:%S.000Z"
        )
        reports = await self._query(
            "reports",
            query=f'[">" , "receive_time", "{cutoff}"]',
            params={
                "limit": "5000",
                "order_by": '[{"field": "receive_time", "order": "desc"}]'
            }
        )
        # Bucket by hour
        from collections import defaultdict
        buckets = defaultdict(lambda: {"changed": 0, "unchanged": 0, "failed": 0})
        for report in reports:
            ts = report.get("receive_time", "")[:13]  # YYYY-MM-DDTHH
            status = report.get("status", "unchanged")
            if status in buckets[ts]:
                buckets[ts][status] += 1

        return [
            {"timestamp": k, "changed": v["changed"],
             "unchanged": v["unchanged"], "failed": v["failed"]}
            for k, v in sorted(buckets.items())
        ][-48:]  # Last 48 data points

    async def get_node_status_trends(self) -> List[Dict]:
        """Get node status trends over time (bucketed by hour from reports).

        Includes ALL known nodes in each bucket -- nodes that didn't
        submit a report in that time window are counted as 'unreported'
        so the chart always reflects the full fleet size, not just the
        nodes that happen to have run recently.
        """
        from collections import defaultdict
        from datetime import datetime, timezone, timedelta
        cutoff = (datetime.now(timezone.utc) - timedelta(hours=48)).strftime(
            "%Y-%m-%dT%H:%M:%S.000Z"
        )
        nodes, reports = await asyncio.gather(
            self.get_nodes(),
            self._query(
                "reports",
                query=f'[">" , "receive_time", "{cutoff}"]',
                params={
                    "limit": "5000",
                    "order_by": '[{"field": "receive_time", "order": "desc"}]'
                }
            ),
        )
        all_certnames = {n.get("certname", "") for n in nodes if n.get("certname")}
        total_nodes = len(all_certnames)

        buckets = defaultdict(lambda: {"unchanged": set(), "changed": set(), "failed": set(), "noop": set()})
        for report in reports:
            ts = report.get("receive_time", "")[:13]  # YYYY-MM-DDTHH
            certname = report.get("certname", "")
            status = report.get("status", "unchanged")
            noop = report.get("noop", False)
            if noop:
                buckets[ts]["noop"].add(certname)
            elif status in buckets[ts]:
                buckets[ts][status].add(certname)

        result = []
        for k, v in sorted(buckets.items()):
            reported = v["unchanged"] | v["changed"] | v["failed"] | v["noop"]
            unreported = total_nodes - len(reported)
            result.append({
                "timestamp": k,
                "unchanged": len(v["unchanged"]),
                "changed": len(v["changed"]),
                "failed": len(v["failed"]),
                "noop": len(v["noop"]),
                "unreported": max(0, unreported),
            })
        return result[-48:]

    async def get_aggregate_event_counts(self) -> Dict:
        """Get aggregate event counts."""
        try:
            result = await self._query(
                "aggregate-event-counts",
                params={"summarize_by": "certname"}
            )
            return result
        except Exception:
            return {}

    async def get_server_time(self) -> Optional[str]:
        """Get PuppetDB server time."""
        try:
            result = await self._query("server-time")
            return result.get("server_time")
        except Exception:
            return None


# Singleton
puppetdb_service = PuppetDBService()
