"""
PuppetDB API client service.

Provides an async HTTP client for communicating with PuppetDB's v4 REST
API over mutual-TLS (using the Puppet agent's SSL certificate and key).
This is the sole gateway for all PuppetDB queries in the application —
every router that needs PuppetDB data goes through the singleton
puppetdb_service instance defined at the bottom of this module.

The client is lazily initialised on first use and reused for the lifetime
of the process. Connection failures are logged and re-raised so that
callers (routers) can return appropriate HTTP error responses.

Security note: several methods accept a report_hash parameter that gets
interpolated into PQL query strings. Report hashes are hex strings
generated by PuppetDB, but because they arrive as user-supplied URL path
parameters, they are validated with a strict hex-only regex before
interpolation to prevent PQL injection.
"""
import asyncio
import re
import httpx
import ssl
import logging
from typing import Any, Dict, List, Optional
from ..config import settings

logger = logging.getLogger(__name__)

# PuppetDB report hashes are SHA-256 hex digests (64 lowercase hex chars).
# This strict pattern prevents PQL injection through crafted hash values
# passed in from URL path parameters.
_SAFE_HEX_HASH = re.compile(r'^[a-f0-9]+$')


def _validate_report_hash(report_hash: str) -> str:
    """Validate that a report hash is a safe hex string for use in PQL.

    PuppetDB report hashes are SHA-256 hex digests, so they should only
    contain lowercase hex characters (a-f, 0-9). Rejecting anything else
    prevents PQL injection through crafted hash values like:
        'abc123"] or true --'
    """
    if not report_hash or not _SAFE_HEX_HASH.match(report_hash):
        raise ValueError(f"Invalid report hash: must be a hex string")
    return report_hash


class PuppetDBService:
    """Async client for PuppetDB v4 API."""

    def __init__(self):
        self.base_url = f"https://{settings.puppetdb_host}:{settings.puppetdb_port}"
        self._client: Optional[httpx.AsyncClient] = None

    def _create_ssl_context(self) -> ssl.SSLContext:
        ctx = ssl.create_default_context(cafile=settings.puppet_ssl_ca)
        ctx.load_cert_chain(
            certfile=settings.puppet_ssl_cert,
            keyfile=settings.puppet_ssl_key,
        )
        return ctx

    async def _get_client(self) -> httpx.AsyncClient:
        if self._client is None or self._client.is_closed:
            self._client = httpx.AsyncClient(
                base_url=self.base_url,
                verify=self._create_ssl_context(),
                timeout=30.0,
            )
        return self._client

    async def close(self):
        if self._client and not self._client.is_closed:
            await self._client.aclose()

    async def _query(self, endpoint: str, query: Optional[str] = None,
                     params: Optional[Dict] = None) -> Any:
        """Execute a PuppetDB query.

        When endpoint is empty, this sends a PQL query to the base
        /pdb/query/v4 endpoint (no trailing slash — PuppetDB returns
        404 for the trailing-slash variant).
        """
        client = await self._get_client()
        url = f"/pdb/query/v4/{endpoint}".rstrip("/")
        request_params = params or {}
        if query:
            request_params["query"] = query
        try:
            resp = await client.get(url, params=request_params)
            resp.raise_for_status()
            return resp.json()
        except httpx.HTTPStatusError as e:
            logger.error(f"PuppetDB HTTP error: {e.response.status_code} - {e.response.text}")
            raise
        except Exception as e:
            logger.error(f"PuppetDB connection error: {e}", exc_info=True)
            raise

    # ─── Nodes ──────────────────────────────────────────────

    async def get_nodes(self, query: Optional[str] = None,
                        include_inactive: bool = False) -> List[Dict]:
        """Get nodes from PuppetDB.

        By default, only returns active nodes (not deactivated or expired)
        and deduplicates by certname. PuppetDB retains deactivated/expired
        node records until they are purged, so filtering is essential to
        avoid displaying ghost nodes that have been removed from the Puppet
        CA but not yet purged from PuppetDB.

        Filtering is done in Python after fetch to guarantee correctness
        regardless of PuppetDB version or PQL operator support.
        """
        all_nodes = await self._query("nodes", query=query)

        if not include_inactive:
            all_nodes = [
                n for n in all_nodes
                if not n.get("deactivated") and not n.get("expired")
            ]

        # Deduplicate by certname (case-insensitive, stripped)
        seen: set = set()
        unique = []
        for node in all_nodes:
            key = node.get("certname", "").strip().lower()
            if key and key not in seen:
                seen.add(key)
                unique.append(node)
        return unique

    async def get_live_nodes(self) -> List[Dict]:
        """Return nodes that exist in **both** active PuppetDB and the CA.

        This is the shared membership source of truth for Overview | Nodes,
        Insights | Inventory, ENC Unclassified / reconciliation, Dashboard,
        and Node Health:

        - **Active PuppetDB** — not deactivated / not expired (ghost factsets
          after expire/deactivate do not count).
        - **Signed CA certificate** — ``puppetserver ca clean`` removes the
          cert; those hosts must disappear everywhere even if PuppetDB has
          not yet expired the node record.

        If the CA list cannot be loaded, falls back to active PuppetDB only
        (still excludes deactivated/expired).
        """
        active = await self.get_nodes(include_inactive=False)
        try:
            from .certificates_service import list_certificates as list_ca_certificates

            cert_data = await list_ca_certificates()
            signed = {
                str(c.get("name", "")).strip().lower()
                for c in (cert_data.get("signed") or [])
                if c.get("name")
            }
        except Exception as e:
            logger.warning(
                "get_live_nodes: CA list unavailable, using active PuppetDB only: %s",
                e,
                exc_info=True,
            )
            return active

        live = [
            n
            for n in active
            if str(n.get("certname", "")).strip().lower() in signed
        ]
        live.sort(key=lambda n: str(n.get("certname", "")).lower())
        return live

    async def get_fleet_nodes(self) -> List[Dict]:
        """Return signed CA certificates enriched with PuppetDB records.

        **Not** the membership SSoT for Overview | Nodes, Inventory, or ENC —
        those use ``get_live_nodes()`` (active PuppetDB ∩ signed CA). This CA
        union is for certificate-centric views and callers that need every
        trusted cert (including signed certs that never reported to PuppetDB).

        - Starts from `puppetserver ca list --all` (signed certs).
        - Enriches every certname with its full PuppetDB record (if present),
          including deactivated/expired nodes (by calling get_nodes with include_inactive).
        - For signed certs that have never appeared in PuppetDB (newly signed,
          never bootstrapped, or long-term orphans not yet cleaned), returns a
          minimal "synthetic" NodeSummary entry with status=None (treated as
          "unreported").
        - Result is always exactly one entry per signed certname, sorted.
        """
        # Domain service (srdevarch1 HP3) — no router import / cycle.
        from .certificates_service import list_certificates as list_ca_certificates

        # Get the authoritative list of signed certs (the fleet)
        try:
            cert_data = await list_ca_certificates()
            signed_certs = cert_data.get("signed", []) if isinstance(cert_data, dict) else []
        except Exception as e:
            logger.warning(f"Failed to load CA signed cert list for fleet nodes: {e}", exc_info=True)
            signed_certs = []

        # Get the richest possible PDB data (active + deactivated + expired)
        # so we can attach status, last report, environment, etc. to matching certs.
        try:
            pdb_nodes = await self.get_nodes(include_inactive=True)
        except Exception as e:
            logger.warning(f"Failed to load full PDB nodes for fleet enrichment: {e}", exc_info=True)
            pdb_nodes = []

        pdb_map: dict[str, dict] = {}
        for n in pdb_nodes:
            k = str(n.get("certname", "")).strip().lower()
            if k:
                pdb_map[k] = n

        fleet: list[dict] = []
        seen: set[str] = set()
        for cert in signed_certs:
            cn = str(cert.get("name", "")).strip()
            k = cn.lower()
            if not cn or k in seen:
                continue
            seen.add(k)

            pdb = pdb_map.get(k)
            if pdb:
                entry = dict(pdb)  # copy the rich record
                # Ensure canonical certname casing from the CA (usually matches)
                entry["certname"] = cn
            else:
                # Signed cert with no PDB record at all → synthetic unreported entry.
                # These are the "lost" nodes that were not appearing on Dashboard/Nodes.
                entry = {
                    "certname": cn,
                    "latest_report_status": None,
                    "report_timestamp": None,
                    "catalog_timestamp": None,
                    "facts_timestamp": None,
                    "report_environment": None,
                    "latest_report_noop": None,
                    "latest_report_corrective_change": None,
                    "deactivated": None,
                    "expired": None,
                }
            fleet.append(entry)

        # Sort alphabetically (consistent with every other node list in the app)
        fleet.sort(key=lambda n: str(n.get("certname", "")).lower())
        return fleet

    async def get_node(self, certname: str) -> Dict:
        """Get a single node by certname."""
        result = await self._query(f"nodes/{certname}")
        return result

    async def get_node_facts(self, certname: str) -> List[Dict]:
        """Get all facts for a node."""
        return await self._query(f"nodes/{certname}/facts")

    async def get_node_resources(self, certname: str) -> List[Dict]:
        """Get all resources for a node."""
        return await self._query(f"nodes/{certname}/resources")

    async def deactivate_node(self, certname: str) -> bool:
        """Deactivate a node in PuppetDB via the command API.

        Sends a 'deactivate node' command directly to PuppetDB's
        /pdb/cmd/v1 endpoint using the existing mTLS connection.
        No sudo or CLI tools needed. Command is async on the PDB side —
        use wait_until_not_active() to verify the node drops out of
        active inventory lists.
        """
        from datetime import datetime, timezone

        client = await self._get_client()
        payload = {
            "command": "deactivate node",
            "version": 3,
            "payload": {
                "certname": certname,
                "producer_timestamp": datetime.now(timezone.utc).isoformat(),
            },
        }
        try:
            resp = await client.post("/pdb/cmd/v1", json=payload)
            resp.raise_for_status()
            logger.info(f"Deactivated node '{certname}' from PuppetDB via command API")
            return True
        except Exception as e:
            logger.warning(f"Failed to deactivate node '{certname}' via PuppetDB API: {e}", exc_info=True)
            return False

    async def is_node_active(self, certname: str) -> Optional[bool]:
        """
        Return True if certname is present as an *active* PuppetDB node,
        False if missing or deactivated/expired, None on query error.
        """
        try:
            key = (certname or "").strip().lower()
            if not key:
                return False
            nodes = await self.get_nodes(include_inactive=True)
            for n in nodes:
                if str(n.get("certname", "")).strip().lower() != key:
                    continue
                if n.get("deactivated") or n.get("expired"):
                    return False
                return True
            return False
        except Exception as e:
            logger.warning(f"is_node_active({certname}): {e}")
            return None

    async def wait_until_not_active(
        self, certname: str, timeout_s: float = 20.0, interval_s: float = 0.75
    ) -> bool:
        """Poll until the node is not in the active PuppetDB set (or timeout)."""
        import time

        deadline = time.monotonic() + timeout_s
        while time.monotonic() < deadline:
            active = await self.is_node_active(certname)
            if active is False:
                return True
            await asyncio.sleep(interval_s)
        # Final check
        return (await self.is_node_active(certname)) is False

    # ─── Reports ────────────────────────────────────────────

    async def get_reports(self, query: Optional[str] = None,
                          limit: int = 50, offset: int = 0,
                          order_by: str = "receive_time",
                          order_dir: str = "desc") -> List[Dict]:
        """Get reports from PuppetDB."""
        params = {
            "limit": str(limit),
            "offset": str(offset),
            "order_by": f'[{{"field": "{order_by}", "order": "{order_dir}"}}]',
        }
        return await self._query("reports", query=query, params=params)

    async def get_report(self, report_hash: str) -> Dict:
        """Get a single report by its SHA-256 hash.

        The hash is validated to contain only hex characters before being
        interpolated into the PQL query to prevent injection attacks.
        """
        report_hash = _validate_report_hash(report_hash)
        results = await self._query(
            "reports",
            query=f'["=", "hash", "{report_hash}"]'
        )
        if results:
            return results[0]
        return {}

    async def get_report_events(self, report_hash: str) -> List[Dict]:
        """Get resource events for a specific report.

        The hash is validated before PQL interpolation.
        """
        report_hash = _validate_report_hash(report_hash)
        return await self._query(
            "events",
            query=f'["=", "report", "{report_hash}"]'
        )

    async def get_report_logs(self, report_hash: str) -> List[Dict]:
        """Get logs for a specific report from PuppetDB's sub-endpoint.

        The hash is validated before being used in the URL path. Returns
        an empty list on failure rather than raising, because log retrieval
        is supplementary to the main report data.
        """
        report_hash = _validate_report_hash(report_hash)
        try:
            return await self._query(f"reports/{report_hash}/logs")
        except Exception as e:
            logger.warning(f"Failed to fetch logs for report {report_hash}: {e}", exc_info=True)
            return []

    async def get_report_metrics(self, report_hash: str) -> List[Dict]:
        """Get metrics for a specific report from PuppetDB's sub-endpoint.

        The hash is validated before being used in the URL path. Returns
        an empty list on failure for the same reason as get_report_logs.
        """
        report_hash = _validate_report_hash(report_hash)
        try:
            return await self._query(f"reports/{report_hash}/metrics")
        except Exception as e:
            logger.warning(f"Failed to fetch metrics for report {report_hash}: {e}", exc_info=True)
            return []

    # ─── Facts ──────────────────────────────────────────────

    async def get_facts(self, fact_name: Optional[str] = None,
                        query: Optional[str] = None) -> List[Dict]:
        """Get facts, optionally filtered by name."""
        endpoint = f"facts/{fact_name}" if fact_name else "facts"
        return await self._query(endpoint, query=query)

    async def get_fact_names(self) -> List[str]:
        """Get all known fact names."""
        return await self._query("fact-names")

    # ─── Environments ───────────────────────────────────────

    async def get_environments(self) -> List[Dict]:
        """Get all environments from PuppetDB."""
        return await self._query("environments")

    # ─── Metrics / Dashboard ────────────────────────────────

    async def get_node_status_counts(self) -> Dict[str, int]:
        """Get node status distribution."""
        nodes = await self.get_nodes()
        counts = {"changed": 0, "unchanged": 0, "failed": 0,
                  "unreported": 0, "noop": 0, "total": len(nodes)}
        for node in nodes:
            status = node.get("latest_report_status")
            if node.get("latest_report_noop"):
                counts["noop"] += 1
            elif status in counts:
                counts[status] += 1
            elif status is None:
                counts["unreported"] += 1
            else:
                counts["unchanged"] += 1
        return counts

    async def get_report_trends(self, hours: int = 24) -> List[Dict]:
        """Get report status trends over time."""
        from datetime import datetime, timezone, timedelta
        cutoff = (datetime.now(timezone.utc) - timedelta(hours=hours)).strftime(
            "%Y-%m-%dT%H:%M:%S.000Z"
        )
        reports = await self._query(
            "reports",
            query=f'[">" , "receive_time", "{cutoff}"]',
            params={
                "limit": "20000",
                "order_by": '[{"field": "receive_time", "order": "desc"}]'
            }
        )
        # Bucket by hour
        from collections import defaultdict
        buckets = defaultdict(lambda: {"changed": 0, "unchanged": 0, "failed": 0})
        for report in reports:
            ts = report.get("receive_time", "")[:13]  # YYYY-MM-DDTHH
            status = report.get("status", "unchanged")
            if status in buckets[ts]:
                buckets[ts][status] += 1

        return [
            {"timestamp": k, "changed": v["changed"],
             "unchanged": v["unchanged"], "failed": v["failed"]}
            for k, v in sorted(buckets.items())
        ][-48:]  # Last 48 data points

    async def get_node_status_trends(self) -> List[Dict]:
        """Get node status trends over time (bucketed by hour from reports).

        Uses a rolling-state model so every hour bucket reflects the full
        fleet, matching the donut chart.  Each node carries its last known
        status forward until a new report updates it.  Nodes that have
        genuinely never reported show as 'unreported'.
        """
        from collections import defaultdict
        from datetime import datetime, timezone, timedelta

        cutoff = (datetime.now(timezone.utc) - timedelta(hours=48)).strftime(
            "%Y-%m-%dT%H:%M:%S.000Z"
        )
        nodes, reports = await asyncio.gather(
            self.get_nodes(),
            self._query(
                "reports",
                query=f'[">" , "receive_time", "{cutoff}"]',
                params={
                    "limit": "20000",
                    "order_by": '[{"field": "receive_time", "order": "asc"}]'
                }
            ),
        )

        # Seed each node's status from PuppetDB's current record.
        # This covers nodes whose last report predates the 48h window.
        node_state: Dict[str, str] = {}
        for n in nodes:
            cn = n.get("certname", "")
            if not cn:
                continue
            if n.get("latest_report_noop"):
                node_state[cn] = "noop"
            elif n.get("latest_report_status"):
                node_state[cn] = n["latest_report_status"]
            else:
                node_state[cn] = "unreported"

        # Group reports by hour bucket (already sorted ascending)
        bucket_reports: Dict[str, list] = defaultdict(list)
        for report in reports:
            ts = report.get("receive_time", "")[:13]  # YYYY-MM-DDTHH
            bucket_reports[ts].append(report)

        all_buckets = sorted(bucket_reports.keys())
        if not all_buckets:
            return []

        result = []
        for bucket in all_buckets:
            # Apply every report in this hour, updating rolling state
            for report in bucket_reports[bucket]:
                cn = report.get("certname", "")
                if cn not in node_state:
                    continue
                if report.get("noop", False):
                    node_state[cn] = "noop"
                else:
                    node_state[cn] = report.get("status", "unchanged")

            # Snapshot the full fleet
            counts = {"unchanged": 0, "changed": 0, "failed": 0,
                      "noop": 0, "unreported": 0}
            for status in node_state.values():
                if status in counts:
                    counts[status] += 1
                else:
                    counts["unchanged"] += 1

            result.append({"timestamp": bucket, **counts})

        return result[-48:]

    async def get_aggregate_event_counts(self) -> Dict:
        """Get aggregate event counts."""
        try:
            result = await self._query(
                "aggregate-event-counts",
                params={"summarize_by": "certname"}
            )
            return result
        except Exception:
            return {}

    async def get_server_time(self) -> Optional[str]:
        """Get PuppetDB server time."""
        try:
            result = await self._query("server-time")
            return result.get("server_time")
        except Exception:
            return None


    # ─── Events (fleet-wide) ─────────────────────────────────

    async def get_events(self, query: Optional[str] = None,
                         limit: int = 500) -> List[Dict]:
        """Get resource events across all nodes."""
        params = {
            "limit": str(limit),
            "order_by": '[{"field": "timestamp", "order": "desc"}]',
        }
        return await self._query("events", query=query, params=params)

    # ─── Catalogs ────────────────────────────────────────────

    async def get_catalog_edges(self, certname: str) -> List[Dict]:
        """Get dependency edges from a node's compiled catalog via PQL."""
        client = await self._get_client()
        query = f'edges {{ certname = "{certname}" }}'
        resp = await client.get("/pdb/query/v4", params={"query": query})
        resp.raise_for_status()
        raw = resp.json()
        # PQL edges return flat fields; normalize to source/target dicts
        edges = []
        for e in raw:
            edges.append({
                "source": {"type": e.get("source_type"), "title": e.get("source_title")},
                "target": {"type": e.get("target_type"), "title": e.get("target_title")},
                "relationship": e.get("relationship"),
            })
        return edges

    async def get_catalog_resources(self, certname: str) -> List[Dict]:
        """Get resources from a node's compiled catalog via PQL."""
        client = await self._get_client()
        query = f'resources {{ certname = "{certname}" }}'
        resp = await client.get("/pdb/query/v4", params={"query": query})
        resp.raise_for_status()
        return resp.json()

    # ─── PuppetDB Health ─────────────────────────────────────

    async def get_pdb_status(self) -> Dict:
        """Query PuppetDB's status endpoint for health info."""
        try:
            client = await self._get_client()
            resp = await client.get("/status/v1/services/puppetdb-status")
            resp.raise_for_status()
            return resp.json()
        except Exception as e:
            logger.warning(f"Failed to get PuppetDB status: {e}", exc_info=True)
            return {}

    async def get_pdb_metrics(self, metric_name: str) -> Dict:
        """Query PuppetDB's JMX metrics endpoint."""
        try:
            client = await self._get_client()
            resp = await client.get(f"/metrics/v2/read/{metric_name}")
            resp.raise_for_status()
            return resp.json()
        except Exception as e:
            logger.warning(f"Failed to get PuppetDB metric {metric_name}: {e}", exc_info=True)
            return {}

    # ─── System Inventory Report ────────────────────────────

    async def get_system_inventory(self) -> List[Dict]:
        """
        Live fleet-wide system inventory report.

        Membership is **active PuppetDB nodes only** (not deactivated / not
        expired) — the same set as ``get_nodes()`` / Overview | Nodes. PuppetDB
        retains factsets for deactivated and expired nodes until GC, so the
        raw ``inventory`` endpoint over-counts vs. the real fleet; we intersect
        with active nodes so Insights | Inventory matches the Nodes list.

        Fact payload still comes from the inventory endpoint (certname + full
        structured facts). Missing facts are empty strings for UI robustness.
        Disks are pre-formatted as newline-separated "name: size" strings.
        """
        # Live membership (SSoT) — active PuppetDB ∩ signed CA.
        live_nodes = await self.get_live_nodes()
        active_keys = {
            str(n.get("certname", "")).strip().lower()
            for n in live_nodes
            if n.get("certname")
        }

        # Full current facts for nodes that have reported factsets.
        # Response items: "certname" + "facts": { ... }.
        raw = await self._query("inventory") or []

        results: List[Dict] = []
        for item in raw:
            certname = item.get("certname", "") or ""
            key = certname.strip().lower()
            if not key or key not in active_keys:
                continue
            facts = item.get("facts") or {}

            # OS
            os_block = facts.get("os") or {}
            os_name = ""
            os_full = ""
            if isinstance(os_block, dict):
                os_name = os_block.get("name") or ""
                rel = os_block.get("release") or {}
                if isinstance(rel, dict):
                    os_full = rel.get("full") or ""
                elif isinstance(rel, str):
                    os_full = rel

            # Physical processors (prefer physicalcount)
            proc = facts.get("processors") or {}
            phys_cpus = ""
            if isinstance(proc, dict):
                phys_cpus = proc.get("physicalcount") or proc.get("count") or ""
            else:
                # In case projection flattened (defensive)
                phys_cpus = facts.get("processors.physicalcount") or facts.get("processors.count") or ""

            # Location (custom fact users often drop via facts.d or external fact)
            location = facts.get("location") or ""

            # Memory (human string preferred)
            mem_block = facts.get("memory") or {}
            memory = ""
            if isinstance(mem_block, dict):
                sysmem = mem_block.get("system") or {}
                if isinstance(sysmem, dict):
                    memory = sysmem.get("total") or ""
                else:
                    memory = mem_block.get("system.total") or ""
            else:
                memory = facts.get("memory.system.total") or ""

            # Disks: dict name -> info; format one "name: size" per line
            disks_block = facts.get("disks") or {}
            disk_lines: List[str] = []
            if isinstance(disks_block, dict):
                for dname in sorted(disks_block.keys()):
                    dinfo = disks_block[dname]
                    if isinstance(dinfo, dict):
                        size = dinfo.get("size") or dinfo.get("size_bytes") or "?"
                        disk_lines.append(f"{dname}: {size}")
                    else:
                        disk_lines.append(f"{dname}: {dinfo}")
            disks = "\n".join(disk_lines)

            # Virtual vs Physical
            # Leverage standard Facter facts: is_virtual (boolean or string) and virtual (type or "physical").
            # This is the authoritative source for "whether a virtual or physical system".
            # See: https://puppet.com/docs/puppet/latest/facter.html (is_virtual / virtual facts)
            is_virt = facts.get("is_virtual")
            virt_val = facts.get("virtual")

            # Normalize is_virtual to boolean (handles bool, "true", "1", "yes", etc.)
            if isinstance(is_virt, bool):
                is_virt_bool = is_virt
            elif isinstance(is_virt, (str, int)):
                is_virt_bool = str(is_virt).strip().lower() in ("true", "1", "yes")
            else:
                is_virt_bool = False

            if is_virt_bool:
                if isinstance(virt_val, str) and virt_val.strip():
                    v = virt_val.strip()
                    if v.lower() not in ("physical", "true", "1"):
                        vlabel = f"Virtual ({v})"
                    else:
                        vlabel = "Virtual"
                else:
                    vlabel = "Virtual"
            else:
                # Fallback to the virtual fact itself (common when is_virtual is false or absent)
                if isinstance(virt_val, str) and virt_val.strip():
                    v = virt_val.strip()
                    if v.lower() not in ("physical", "false", "0", ""):
                        vlabel = f"Virtual ({v})"
                    else:
                        vlabel = "Physical"
                else:
                    vlabel = "Physical"

            # Uptime (prefer the human 'uptime' string)
            up_block = facts.get("system_uptime") or {}
            uptime = ""
            if isinstance(up_block, dict):
                uptime = up_block.get("uptime") or ""
            if not uptime:
                uptime = facts.get("uptime") or facts.get("system_uptime.uptime") or ""

            results.append({
                "certname": certname,
                "os_name": os_name,
                "os_full_release": os_full,
                "physical_processors": phys_cpus,
                "location": location,
                "memory": memory,
                "disks": disks,
                "virtual_physical": vlabel,
                "uptime": uptime,
            })

        # Stable sort by certname (case-insensitive) like other lists
        results.sort(key=lambda r: (r.get("certname") or "").lower())
        return results


# Singleton
puppetdb_service = PuppetDBService()
